apiVersion: v1
kind: ConfigMap
metadata:
   name: myconfigmap
data:
   api.username: rocky
   api.firstname: surjeet
   api.lastname: mohanty
   
---
apiVersion: v1
kind: Secret
metadata:
   name: mysecret
data:
   api.secret: aGliZXJAMTIz
